_BASE_: continual_maskformer2_R101_bs8_160k.yaml
CONT:
  TOT_CLS: 150
  BASE_CLS: 100
  INC_CLS: 50
  TASK: 1
  LIB_SIZE: 80
  PSD_LABEL_THRESHOLD: 0.45
  VQ_NUMBER: 1
  FREEZE_LABEL: False
  DISTRIBUTION_ALPHA: 0.25
MODEL:
  MASK_FORMER:
    TEST:
      OBJECT_MASK_THRESHOLD: 0.8
OUTPUT_DIR: ./output/ss/100-10_test/step1
