_BASE_: continual_maskformer2_R101_bs8_160k.yaml
CONT:
  TOT_CLS: 150
  BASE_CLS: 100
  INC_CLS: 5
  TASK: 1
  LIB_SIZE: 80
  PSD_LABEL_THRESHOLD: 0.0
  PSD_OVERLAP_THRESHOLD : 0.8
  VQ_NUMBER: 5
  FREEZE_LABEL: True
  KL_WEIGHT : 4.0
  KL_ALL : False
  KD_TEMPERATURE : 0.1
  KD_TEMPERATURE2 : 0.1
  FILTER_KD : False
SOLVER:
  STEPS: (1700, 1900)
MODEL:
  RESNETS:
    NORM : "SyncBN"
  MASK_FORMER:
    TEST:
      OBJECT_MASK_THRESHOLD: 0.8
OUTPUT_DIR: ./output/ss/100-10_test/step1
