_BASE_: continual_maskformer2_R50_bs8_160k.yaml
CONT:
  TOT_CLS: 150
  BASE_CLS: 100
  INC_CLS: 5
  TASK: 1
  LIB_SIZE: 80
  PSD_LABEL_THRESHOLD: 0.35
  VQ_NUMBER: 3
  FREEZE_LABEL: False
  KL_WEIGHT : 2.0
  KL_ALL : True
  KD_TEMPERATURE : 1.0
  KD_TEMPERATURE2 : 1.0
  FILTER_KD : False
SOLVER:
  STEPS: (1700, 1900)
MODEL:
  RESNETS:
    NORM : "SyncBN"
  MASK_FORMER:
    TEST:
      OBJECT_MASK_THRESHOLD: 0.25
OUTPUT_DIR: ./output/ps/100-5/step1