_BASE_: continual_maskformer2_swin_bs8_160k.yaml
CONT:
  TOT_CLS: 150
  BASE_CLS: 100
  INC_CLS: 10
  TASK: 1
SOLVER:
  CHECKPOINT_PERIOD: 1000000
OUTPUT_DIR: ./output/ps/100-10/step1
TEST:
  EVAL_PERIOD: 5000000