_BASE_: continual_maskformer2_R50_bs8_160k.yaml
CONT:
  TOT_CLS: 150
  BASE_CLS: 100
  INC_CLS: 50
  TASK: 1
  VQ_NUMBER: 1
  DISTRIBUTION_ALPHA: 0.25
SOLVER:
  STEPS: (42500, 47500)
MODEL:
  MASK_FORMER:
    TEST:
      OBJECT_MASK_THRESHOLD: 0.20
OUTPUT_DIR: ./output/ps/100-50/step1