_BASE_: continual_maskformer2_R50_bs8_160k.yaml
CONT:
  TOT_CLS: 150
  BASE_CLS: 50
  INC_CLS: 50
  TASK: 1
  PSD_LABEL_THRESHOLD: 0.35
SOLVER:
  STEPS: (42500, 47500)
OUTPUT_DIR: ./output/ps/50-50/step1