_BASE_: "maskformer2_R50_bs16_160k.yaml"
INPUT:
  DATASET_MAPPER_NAME: "continual_panoptic"
DATASETS:
  TRAIN: ("current_ade20k_panoptic_train",)
  TEST: ("current_ade20k_panoptic_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 10000
CONT:
  SETTING: "overlapped"
  MED_TOKENS_WEIGHT: 5.0
  MEMORY: False # We don't use replay in  experiment.
  KD_DECODER: False
TEST:
  EVAL_PERIOD: 2501
MODEL:
  MASK_FORMER:
    USE_TEXT_EMBEDDING: False
    TEXT_PATH: "label_embedding/ade20k_150_laion768_all.npy"
    CLIP_DIM: 768